AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Testes com Typescript
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MarvelCharactersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/marvelCharacters
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Role: MarvelCharactersFunctionRole
      Events:
        getCharacter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /marvelCharacters
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MarvelCharactersApi:
    Description: "API Gateway endpoint URL for Prod stage for Marvel Character function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/marvelCharacters/"
  MarvelCharactersFunction:
    Description: "Marvel character Lambda Function ARN"
    Value: !GetAtt MarvelCharactersFunction.Arn
  MarvelCharactersFunctionIamRole:
    Description: "Implicit IAM Role created for MarvelCharacter function"
    Value: !GetAtt MarvelCharactersFunctionRole.Arn
